-- Voucher numbering series. Every transaction master points at BillTypeId,
-- and user.Def*BillType / organization.DefCust*BillType hold eleven more
-- references -- none of them constrained in MySQL, none constrained here.
--
-- StartNumber is allocation state in the same sense as counters.val.

CREATE TABLE IF NOT EXISTS billtype (
    "billtype_id"      integer      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "OrganizationCode" varchar(4)   NOT NULL,
    "BillTypeId"       varchar(20)  NOT NULL,
    "BillTypeName"     varchar(50)  NOT NULL,
    "StartNumber"      integer      NOT NULL,
    "Prefix"           varchar(10)  NOT NULL,
    "Suffix"           varchar(10)  NOT NULL,
    "VoucherType"      varchar(5)   NOT NULL,
    "TaxType"          varchar(20)  NOT NULL DEFAULT '',
    "CreatedByUser"    varchar(20)  NOT NULL,
    "CreatedTimeStamp" timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),

    CONSTRAINT billtype_pkey PRIMARY KEY ("billtype_id")
);

ALTER TABLE billtype OWNER TO firefly_app;
