-- Inventory groups. ParentGroup is a self-reference to InventoryGroupId, stored
-- as a bare string with no constraint -- the hierarchy is resolved in PHP.

CREATE TABLE IF NOT EXISTS category (
    "cat_id"           integer      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "OrganizationCode" varchar(4)   NOT NULL,  -- char(4) in MySQL
    "InventoryGroupId" varchar(20)  NOT NULL,
    "GroupName"        varchar(50)  NOT NULL,
    "ParentGroup"      varchar(20)  NOT NULL,
    "ImagePath"        varchar(200) NOT NULL DEFAULT 'no_image.jpg',
    "Colour"           varchar(50)  NOT NULL,

    CONSTRAINT category_pkey PRIMARY KEY ("cat_id")
);

ALTER TABLE category OWNER TO firefly_app;
