-- Routes an inventory group's items to a kitchen printer. Machine-local
-- (holds LAN IPs). InventoryGroupId is varchar(31) here but varchar(20) on
-- category -- mirrored as declared.

CREATE TABLE IF NOT EXISTS gatepass (
    "autoid"           integer      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "InventoryGroupId" varchar(31)  NOT NULL,
    "GroupName"        varchar(100) NOT NULL,
    "PrinterIp"        varchar(50)  NOT NULL,
    "Port"             integer      NOT NULL DEFAULT 9100,
    "Type"             varchar(50)  NOT NULL,
    "IsActive"         smallint     NOT NULL DEFAULT 1,
    "PrinterId"        integer,

    CONSTRAINT gatepass_pkey PRIMARY KEY ("autoid")
);

ALTER TABLE gatepass OWNER TO firefly_app;
