-- Customers, suppliers and bank accounts in one table, discriminated by
-- LedgerType ('P' party, 'B' bank).
--
-- mypassword is a customer-portal credential stored in the clear. It is
-- mirrored here so the schema matches, but copying its values across is a
-- security decision, not a data-copy decision.

CREATE TABLE IF NOT EXISTS ledger (
    "led_id"           integer       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "OrganizationCode" varchar(4)    NOT NULL,
    "CentreCode"       varchar(4)    NOT NULL,
    "LedgerId"         varchar(20)   NOT NULL,
    "LedgerType"       varchar(1)    NOT NULL,  -- char(1) in MySQL
    "LedgerName"       varchar(50)   NOT NULL,
    "RegionalName"     varchar(100)  NOT NULL,
    "Address"          varchar(100)  NOT NULL,
    "Email"            varchar(50)   NOT NULL,
    "Phone"            varchar(15)   NOT NULL,
    "UserName"         varchar(50)   NOT NULL,
    "mypassword"       varchar(500)  NOT NULL,
    "noofseats"        integer       NOT NULL,  -- int(2); MySQL display widths mean nothing
    "seatstaken"       integer       NOT NULL,  -- int(2)
    "CurrentBalance"   numeric(24,8) NOT NULL,
    "LedgerCode"       varchar(10)   NOT NULL,
    "CustomCode"       varchar(50)   NOT NULL,
    "RoutId"           varchar(20)   NOT NULL,
    "TINNumber"        varchar(50)   NOT NULL,
    "IsActive"         smallint      NOT NULL DEFAULT 1,

    CONSTRAINT ledger_pkey PRIMARY KEY ("led_id")
);

ALTER TABLE ledger OWNER TO firefly_app;
