-- Order cancellation line items. OrderDetailsId points at
-- orderdetails."orderdtl_id" -- an integer reference, unlike everything else
-- in the schema, which joins on opaque strings.

CREATE TABLE IF NOT EXISTS ordercanceldetails (
    "OrderCancelDetailsId" integer       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "OrderCancelMasterId"  varchar(31)   NOT NULL,
    "OrderDetailsId"       integer       NOT NULL,
    "InventoryDetailsId"   varchar(31)   NOT NULL,
    "UnitId"               varchar(20)   NOT NULL,
    "Quantity"             numeric(24,8) NOT NULL,
    "Rate"                 numeric(24,8) NOT NULL,
    "TotalAmount"          numeric(24,8) NOT NULL,
    "Description"          varchar(500)  NOT NULL,
    "CreatedByUser"        varchar(20)   NOT NULL,
    "CreatedTimeStamp"     timestamp(0)  NOT NULL DEFAULT LOCALTIMESTAMP(0),

    CONSTRAINT ordercanceldetails_pkey PRIMARY KEY ("OrderCancelDetailsId")
);

CREATE INDEX IF NOT EXISTS ordercanceldetails_idx_ocd_orderdetailsid ON ordercanceldetails ("OrderDetailsId");

ALTER TABLE ordercanceldetails OWNER TO firefly_app;
