-- Order line items. `ordermstr_id` is snake_case while its parent column is
-- ordermaster."OrderMasterId" -- mirrored as declared.

CREATE TABLE IF NOT EXISTS orderdetails (
    "orderdtl_id"        integer       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "ordermstr_id"       varchar(31)   NOT NULL,
    "InventoryDetailsId" varchar(31)   NOT NULL,
    "UnitId"             varchar(20)   NOT NULL,
    "Quantity"           numeric(24,8) NOT NULL,
    "Rate"               numeric(24,8) NOT NULL,
    "TotalAmount"        numeric(24,8) NOT NULL,
    "Description"        varchar(500)  NOT NULL,
    "CreatedByUser"      varchar(20)   NOT NULL,
    "CreatedTimeStamp"   timestamp(0)  NOT NULL DEFAULT LOCALTIMESTAMP(0),

    CONSTRAINT orderdetails_pkey PRIMARY KEY ("orderdtl_id")
);

CREATE INDEX IF NOT EXISTS orderdetails_idx_orderdetails_ordermstr ON orderdetails ("ordermstr_id");

ALTER TABLE orderdetails OWNER TO firefly_app;
