-- Per-user defaults for a POS mode. One of only two tables carrying a real
-- foreign key in MySQL, so the reference is replicated here -- including
-- ON DELETE CASCADE.

CREATE TABLE IF NOT EXISTS pos_user_mode_prefs (
    "id"         integer      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id"    varchar(40)  NOT NULL,
    "mode_id"    integer      NOT NULL,
    "ledger"     varchar(40),
    "billtype"   varchar(40),
    "paymode"    varchar(20)  NOT NULL DEFAULT 'CASH',
    "bank"       varchar(40),
    "auto_print" smallint     NOT NULL DEFAULT 1,
    "print_bill" smallint     NOT NULL DEFAULT 1,
    "print_kot"  smallint     NOT NULL DEFAULT 0,
    "created_at" timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
    "updated_at" timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),

    CONSTRAINT pos_user_mode_prefs_pkey PRIMARY KEY ("id"),
    CONSTRAINT uk_user_mode UNIQUE ("user_id", "mode_id"),
    CONSTRAINT fk_pump_mode FOREIGN KEY ("mode_id") REFERENCES pos_modes ("id") ON DELETE CASCADE
);

DROP TRIGGER IF EXISTS pos_user_mode_prefs_set_updated_at ON pos_user_mode_prefs;
CREATE TRIGGER pos_user_mode_prefs_set_updated_at
    BEFORE UPDATE ON pos_user_mode_prefs
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

ALTER TABLE pos_user_mode_prefs OWNER TO firefly_app;
