-- POS operating modes (dine-in, takeaway, ...). The only table other code
-- declares a real foreign key against, so it must be created before
-- pos_mode_print_targets and pos_user_mode_prefs.

CREATE TABLE IF NOT EXISTS pos_modes (
    "id"                integer      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "mode_key"          varchar(40)  NOT NULL,
    "mode_uid"          varchar(40),
    "label"             varchar(60)  NOT NULL,
    "icon"              varchar(60),
    "color"             varchar(20),
    "sort_order"        integer      NOT NULL DEFAULT 0,
    "is_active"         smallint     NOT NULL DEFAULT 1,
    "default_ledger"    varchar(40),
    "default_billtype"  varchar(40),
    "default_rate_type" varchar(20),
    "voucher_type"      varchar(2)   NOT NULL DEFAULT 'SI',
    "kot_routing"       varchar(8)   NOT NULL DEFAULT 'single',
    "default_paymode"   varchar(20)  NOT NULL DEFAULT 'CASH',
    "default_bank"      varchar(40),
    "description_tag"   varchar(120),
    "created_at"        timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
    "updated_at"        timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),

    CONSTRAINT pos_modes_pkey PRIMARY KEY ("id"),
    CONSTRAINT chk_pos_modes_voucher_type CHECK ("voucher_type" IN ('SI', 'SO')),
    CONSTRAINT chk_pos_modes_kot_routing  CHECK ("kot_routing" IN ('single', 'gatepass'))
);

-- Both engines allow repeated NULLs under a unique index, so nullable mode_uid
-- behaves the same on either side.
CREATE UNIQUE INDEX IF NOT EXISTS pos_modes_uk_pos_modes_key ON pos_modes ("mode_key");
CREATE UNIQUE INDEX IF NOT EXISTS pos_modes_uk_pos_modes_uid ON pos_modes ("mode_uid");

DROP TRIGGER IF EXISTS pos_modes_set_updated_at ON pos_modes;
CREATE TRIGGER pos_modes_set_updated_at
    BEFORE UPDATE ON pos_modes
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

ALTER TABLE pos_modes OWNER TO firefly_app;
