-- Which printer and template each POS mode uses, per printer role. The second
-- and last table with a real MySQL foreign key.

CREATE TABLE IF NOT EXISTS pos_mode_print_targets (
    "id"            integer      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "mode_id"       integer      NOT NULL,
    "printer_role"  varchar(6),
    "printer_id"    integer,
    "template"      varchar(14)  NOT NULL DEFAULT 'full_bill',
    "template_id"   integer,
    "print_mode"    varchar(8)   NOT NULL DEFAULT 'escpos',
    "paper_width"   varchar(20),
    "copies"        integer      NOT NULL DEFAULT 1,
    "trigger_event" varchar(7)   NOT NULL DEFAULT 'manual',
    "sort_order"    integer      NOT NULL DEFAULT 0,
    "is_active"     smallint     NOT NULL DEFAULT 1,
    "created_at"    timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
    "updated_at"    timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),

    CONSTRAINT pos_mode_print_targets_pkey PRIMARY KEY ("id"),
    CONSTRAINT fk_mpt_mode FOREIGN KEY ("mode_id") REFERENCES pos_modes ("id") ON DELETE CASCADE,
    CONSTRAINT chk_pmpt_printer_role  CHECK ("printer_role" IN ('bill', 'kot', 'parcel', 'bar', 'pickup')),
    CONSTRAINT chk_pmpt_template      CHECK ("template" IN ('full_bill', 'packing_slip', 'kitchen_ticket', 'label', 'bar_ticket')),
    CONSTRAINT chk_pmpt_print_mode    CHECK ("print_mode" IN ('escpos', 'html', 'compiled')),
    CONSTRAINT chk_pmpt_trigger_event CHECK ("trigger_event" IN ('on_save', 'on_pay', 'manual'))
);

CREATE INDEX IF NOT EXISTS pos_mode_print_targets_idx_mpt_mode ON pos_mode_print_targets ("mode_id");

DROP TRIGGER IF EXISTS pos_mode_print_targets_set_updated_at ON pos_mode_print_targets;
CREATE TRIGGER pos_mode_print_targets_set_updated_at
    BEFORE UPDATE ON pos_mode_print_targets
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

ALTER TABLE pos_mode_print_targets OWNER TO firefly_app;
