-- Receipt/KOT layouts. layout_json and compiled_json are the only large payloads
-- in the schema (longtext in MySQL).

CREATE TABLE IF NOT EXISTS print_templates (
    "id"            integer      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name"          varchar(120) NOT NULL,
    "kind"          varchar(6)   NOT NULL DEFAULT 'bill',
    "paper_width"   varchar(20)  NOT NULL DEFAULT '80mm',
    "engine"        varchar(8)   NOT NULL DEFAULT 'compiled',
    "layout_json"   text         NOT NULL,
    "compiled_json" text,
    "compile_hash"  varchar(64),
    "compiled_at"   timestamp(0),
    "is_default"    smallint     NOT NULL DEFAULT 0,
    "is_active"     smallint     NOT NULL DEFAULT 1,
    "created_at"    timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
    "updated_at"    timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),

    CONSTRAINT print_templates_pkey PRIMARY KEY ("id"),
    CONSTRAINT chk_print_templates_kind   CHECK ("kind" IN ('bill', 'kot', 'parcel', 'bar')),
    CONSTRAINT chk_print_templates_engine CHECK ("engine" IN ('compiled', 'html'))
);

-- MySQL index names are per-table; PostgreSQL's are schema-global, and
-- idx_inventory alone would collide between product_images and substock. Every
-- index is therefore prefixed with its table name. Index names are never on the
-- wire, so this costs nothing.
CREATE INDEX IF NOT EXISTS print_templates_idx_pt_kind ON print_templates ("kind", "is_active");

DROP TRIGGER IF EXISTS print_templates_set_updated_at ON print_templates;
CREATE TRIGGER print_templates_set_updated_at
    BEFORE UPDATE ON print_templates
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

ALTER TABLE print_templates OWNER TO firefly_app;
