-- Physical printer definitions. Machine-local: holds LAN IPs and OS printer names.
--
-- MySQL enums become varchar + CHECK. A native PostgreSQL ENUM would serialise
-- identically, but there are 17 enum columns across the schema and each would
-- need its own type declaration plus an ALTER TYPE dance to add a label.
-- varchar keeps the wire bytes the same and stays editable.

CREATE TABLE IF NOT EXISTS printers (
    "Id"            integer      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name"          varchar(100) NOT NULL,
    "Mode"          varchar(7)   NOT NULL,
    "IpAddress"     varchar(50),
    "Port"          integer      DEFAULT 9100,
    "SystemName"    varchar(150),
    "PaperWidth"    varchar(4)   DEFAULT '80mm',
    "Type"          varchar(5)   DEFAULT 'EPSON',
    "CharacterSet"  varchar(50)  DEFAULT 'PC437_USA',
    "TimeoutMs"     integer      DEFAULT 5000,
    "IsActive"      smallint     DEFAULT 1,
    "PrintBehavior" varchar(10)  NOT NULL DEFAULT 'split_only',
    "CreatedAt"     timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),

    CONSTRAINT printers_pkey PRIMARY KEY ("Id"),
    -- A CHECK passes when the expression is NULL, so the nullable columns below
    -- accept NULL without any extra clause -- same as the MySQL enums.
    CONSTRAINT chk_printers_mode           CHECK ("Mode" IN ('Network', 'Usb', 'Pdf', 'Kiosk')),
    CONSTRAINT chk_printers_paperwidth     CHECK ("PaperWidth" IN ('80mm', '58mm')),
    CONSTRAINT chk_printers_type           CHECK ("Type" IN ('EPSON', 'STAR')),
    CONSTRAINT chk_printers_printbehavior  CHECK ("PrintBehavior" IN ('split_only', 'full_order', 'both', 'disabled'))
);

ALTER TABLE printers OWNER TO firefly_app;
