-- Product image gallery, keyed on the product business key rather than prod_id.

CREATE TABLE IF NOT EXISTS product_images (
    "ImageId"            integer      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "InventoryDetailsId" varchar(31)  NOT NULL,
    "ImagePath"          varchar(255) NOT NULL,
    "IsPrimary"          smallint     DEFAULT 0,
    "CreatedAt"          timestamp(0) DEFAULT LOCALTIMESTAMP(0),

    CONSTRAINT product_images_pkey PRIMARY KEY ("ImageId")
);

CREATE INDEX IF NOT EXISTS product_images_idx_inventory ON product_images ("InventoryDetailsId");

ALTER TABLE product_images OWNER TO firefly_app;
