-- The catalogue.
--
-- Two things here look like bugs and must not be "fixed":
--
--   1. Every price column is varchar(50), not a numeric type. Converting them
--      would change the wire format from "120.00" to 120.00 and break every
--      client that reads them as strings.
--
--   2. isVeg is the schema's only bit(1). Verified against the live stack:
--      PDO returns it as a PHP integer and json_encode emits a bare 1, so
--      smallint reproduces it exactly (node-postgres parses int2 as a JS
--      number). A boolean would emit true/false instead.

CREATE TABLE IF NOT EXISTS product (
    "OrganizationCode"    varchar(4)   NOT NULL,  -- char(4) in MySQL
    "prod_id"             integer      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "UnitId"              varchar(20)  NOT NULL,
    "UnitName"            varchar(50)  NOT NULL,
    "UnitShortName"       varchar(50)  NOT NULL,
    "ProductName"         varchar(100) NOT NULL,
    "ImagePath"           varchar(100) NOT NULL,
    "InventoryDetailsId"  varchar(31)  NOT NULL,
    "InventoryGroupId"    varchar(20)  NOT NULL,
    "MRP"                 varchar(50)  NOT NULL,
    "MOP"                 varchar(50)  NOT NULL,
    "MLOP"                varchar(50)  NOT NULL,
    "PurchaseRate"        varchar(50)  NOT NULL,
    "AvgRate"             varchar(50)  NOT NULL,
    "LastPurchaseRate"    varchar(50)  NOT NULL,
    "SaleRate"            varchar(50)  NOT NULL,
    "isVeg"               smallint     NOT NULL,  -- bit(1) in MySQL; see note above
    "Description"         varchar(100) NOT NULL,
    "CurrentStock"        integer      NOT NULL,
    "OrderLimit"          integer      NOT NULL,
    "TaxId"               varchar(20)  NOT NULL,
    "AddTaxId"            varchar(20)  NOT NULL,
    "AddTaxId1"           varchar(20)  NOT NULL,
    "Barcode"             varchar(20)  NOT NULL,
    "CustomBarcode"       varchar(50)  NOT NULL,
    "Code"                varchar(50)  NOT NULL,
    "HSNCode"             varchar(30)  NOT NULL,
    -- These two are declared CHARACTER SET utf8 (3-byte) in MySQL while the rest
    -- of the table is utf8mb4. PostgreSQL is UTF-8 throughout, so they simply
    -- hold more than MySQL would accept -- a widening, not a divergence.
    "Size"                varchar(10)  NOT NULL,
    "Colour"              varchar(50)  NOT NULL,
    "ProductRegionalName" varchar(100) NOT NULL,
    "UnitRegionalName"    varchar(100) NOT NULL,
    "StockMaster"         integer      NOT NULL DEFAULT 0,

    CONSTRAINT product_pkey PRIMARY KEY ("prod_id")
);

-- InventoryDetailsId is the business key every other table joins on, but MySQL
-- indexes it non-uniquely. Kept non-unique: making it unique could reject rows
-- the PHP API writes today.
CREATE INDEX IF NOT EXISTS product_idx_product_inventory ON product ("InventoryDetailsId");

ALTER TABLE product OWNER TO firefly_app;
