-- Purchase order line items. Same shape as orderdetails but with OrderQuantity
-- instead of Quantity, plus UpdatedQuantity for partial receipts.
-- ordermstr_id points at purchaseordermaster."ordermasterId".

CREATE TABLE IF NOT EXISTS purchaseorderdetails (
    "orderdtl_id"        integer       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "ordermstr_id"       varchar(31)   NOT NULL,
    "InventoryDetailsId" varchar(31)   NOT NULL,
    "UnitId"             varchar(20)   NOT NULL,
    "OrderQuantity"      numeric(24,8) NOT NULL,
    "Rate"               numeric(24,8) NOT NULL,
    "TotalAmount"        numeric(24,8) NOT NULL,
    "Description"        varchar(500)  NOT NULL,
    "CreatedByUser"      varchar(20)   NOT NULL,
    "CreatedTimeStamp"   timestamp(0)  NOT NULL DEFAULT LOCALTIMESTAMP(0),
    "UpdatedQuantity"    numeric(24,8) NOT NULL,

    CONSTRAINT purchaseorderdetails_pkey PRIMARY KEY ("orderdtl_id")
);

ALTER TABLE purchaseorderdetails OWNER TO firefly_app;
