-- Delivery routes. Referenced by ledger.RoutId and user.Routid (note the
-- differing case on the user side -- both are plain varchars, no constraint).

CREATE TABLE IF NOT EXISTS rout (
    "rt_id"  integer     NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "RoutId" varchar(20) NOT NULL,
    "Name"   varchar(20) NOT NULL,

    CONSTRAINT rout_pkey PRIMARY KEY ("rt_id")
);

ALTER TABLE rout OWNER TO firefly_app;
