-- Delivery routes. Referenced by ledger.RoutId and user.RoutId -- both plain
-- varchars, no constraint. (MySQL declares the user-side column "Routid"; see
-- the note in user.sql for why this port spells it RoutId.)

CREATE TABLE IF NOT EXISTS rout (
    "rt_id"  integer     NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "RoutId" varchar(20) NOT NULL,
    "Name"   varchar(20) NOT NULL,

    CONSTRAINT rout_pkey PRIMARY KEY ("rt_id")
);

ALTER TABLE rout OWNER TO firefly_app;
