-- Sales return line items. Column-for-column identical to salesdetails, with
-- SaleReturnDetailsId as the key and SaleReturnMasterId as the parent. MySQL
-- gives this one no secondary index, unlike salesdetails.

CREATE TABLE IF NOT EXISTS salesreturndetails (
    "SaleReturnDetailsId" integer       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "SaleReturnMasterId"  varchar(31)   NOT NULL,
    "InventoryDetailsId"  varchar(31)   NOT NULL,
    "UnitId"              varchar(20)   NOT NULL,
    "Quantity"            numeric(24,8) NOT NULL,
    "Rate"                numeric(24,8) NOT NULL,
    "GrossAmount"         numeric(24,8) NOT NULL,
    "DiscountPercentage"  numeric(5,2)  NOT NULL,
    "DiscountAmount"      numeric(24,8) NOT NULL,
    "TaxId"               varchar(20)   NOT NULL,
    "TaxableAmount"       numeric(24,8) NOT NULL,
    "TaxPercentage"       numeric(5,2)  NOT NULL,
    "TaxAmount"           numeric(24,8) NOT NULL,
    "TotalAmount"         numeric(24,8) NOT NULL,
    "CreatedByUser"       varchar(20)   NOT NULL,
    "CreatedTimeStamp"    timestamp(0)  NOT NULL DEFAULT LOCALTIMESTAMP(0),
    "Description"         varchar(500)  NOT NULL,
    "AddTaxId"            varchar(20)   NOT NULL,
    "AddTaxPercentage"    numeric(5,2)  NOT NULL,
    "AddTaxAmount"        numeric(24,8) NOT NULL,
    "AddTaxId1"           varchar(20)   NOT NULL,
    "AddTaxPercentage1"   numeric(5,2)  NOT NULL,
    "AddTaxAmount1"       numeric(24,8) NOT NULL,

    CONSTRAINT salesreturndetails_pkey PRIMARY KEY ("SaleReturnDetailsId")
);

ALTER TABLE salesreturndetails OWNER TO firefly_app;
