-- Candidate API URLs offered by the ERP's settings screen. Machine-local.

CREATE TABLE IF NOT EXISTS settings_urls (
    "id"         integer       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "url"        varchar(1000) NOT NULL,
    "label"      varchar(255),
    "created_at" timestamp(0)  NOT NULL DEFAULT LOCALTIMESTAMP(0),

    CONSTRAINT settings_urls_pkey PRIMARY KEY ("id")
);

ALTER TABLE settings_urls OWNER TO firefly_app;
