-- UPI payment addresses. OrganizationCode is varchar(20) here while every other
-- table declares varchar(4)/char(4); mirrored as-is rather than "corrected".

CREATE TABLE IF NOT EXISTS settings_upi (
    "UpiId"            integer      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "OrganizationCode" varchar(20)  NOT NULL,
    "UpiAddress"       varchar(100) NOT NULL,
    "IsDefault"        smallint     DEFAULT 0,
    "IsActive"         smallint     DEFAULT 1,
    "CreatedAt"        timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),

    CONSTRAINT settings_upi_pkey PRIMARY KEY ("UpiId")
);

ALTER TABLE settings_upi OWNER TO firefly_app;
