-- The stock ledger: one row per line item per voucher. The only table in the
-- schema with unbounded growth.
--
-- MasterId is polymorphic -- it holds a salemaster."SaleMasterId" or an
-- ordermaster."OrderMasterId" depending on VoucherType, which is why it can
-- never carry a foreign key. InventoryDetailsId is varchar(50) here against
-- product's varchar(31); mirrored as declared.

CREATE TABLE IF NOT EXISTS stockposting (
    "id"                 integer       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "InventoryDetailsId" varchar(50)   NOT NULL,
    "VoucherType"        varchar(10)   NOT NULL,
    "VoucherNumber"      varchar(30),
    "Qty"                numeric(18,4) NOT NULL,
    "Unit"               varchar(20)   NOT NULL DEFAULT 'No',
    "WarehouseId"        varchar(50),
    "MasterId"           varchar(50),
    "Direction"          varchar(1)    NOT NULL DEFAULT 'I',
    "VoucherDate"        timestamp(0)  NOT NULL DEFAULT LOCALTIMESTAMP(0),
    "CreatedAt"          timestamp(0)  NOT NULL DEFAULT LOCALTIMESTAMP(0),

    CONSTRAINT stockposting_pkey PRIMARY KEY ("id"),
    CONSTRAINT chk_stockposting_direction CHECK ("Direction" IN ('I', 'O'))
);

CREATE INDEX IF NOT EXISTS stockposting_idx_inv_wh       ON stockposting ("InventoryDetailsId", "WarehouseId");
CREATE INDEX IF NOT EXISTS stockposting_idx_master_type  ON stockposting ("MasterId", "VoucherType", "Direction");
CREATE INDEX IF NOT EXISTS stockposting_idx_voucher_date ON stockposting ("VoucherDate");

ALTER TABLE stockposting OWNER TO firefly_app;
