-- Unit conversions: a master SKU to its sub-SKU, with a conversion factor.
-- A self-junction on product.InventoryDetailsId.

CREATE TABLE IF NOT EXISTS substock (
    "id"                       integer       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "MasterInventoryDetailsId" varchar(31)   NOT NULL,
    "InventoryDetailsId"       varchar(31)   NOT NULL,
    "ConversionFactor"         numeric(10,4) NOT NULL DEFAULT 0.0000,
    "CreatedByUser"            varchar(100)  NOT NULL,
    "created_at"               timestamp(0)  NOT NULL DEFAULT LOCALTIMESTAMP(0),
    "IsActive"                 smallint      NOT NULL DEFAULT 1,
    "UpdatedAt"                timestamp(0)  NOT NULL DEFAULT LOCALTIMESTAMP(0),

    CONSTRAINT substock_pkey PRIMARY KEY ("id"),
    CONSTRAINT uq_master_sub UNIQUE ("MasterInventoryDetailsId", "InventoryDetailsId")
);

CREATE INDEX IF NOT EXISTS substock_idx_master    ON substock ("MasterInventoryDetailsId");
CREATE INDEX IF NOT EXISTS substock_idx_inventory ON substock ("InventoryDetailsId");

-- The only ON UPDATE column spelled "UpdatedAt" rather than updated_at.
DROP TRIGGER IF EXISTS substock_set_updated_at ON substock;
CREATE TRIGGER substock_set_updated_at
    BEFORE UPDATE ON substock
    FOR EACH ROW EXECUTE FUNCTION set_updatedat_camel();

ALTER TABLE substock OWNER TO firefly_app;
