-- Tax rates. Referenced by product, salemaster, salesdetails, salesreturndetails
-- via TaxId -- which, despite being the business key, carries no unique
-- constraint in MySQL. Not adding one: duplicate TaxIds are apparently tolerated
-- and rejecting them here would break writes that succeed today.

CREATE TABLE IF NOT EXISTS taxdetails (
    "AUTOID"          integer      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "TaxId"           varchar(20)  NOT NULL,
    "TaxName"         varchar(50)  NOT NULL,
    "Rate"            numeric(10,3) NOT NULL,
    "CalculatingMode" varchar(2)   NOT NULL,  -- char(2) in MySQL
    "TaxType"         varchar(1)   NOT NULL,  -- char(1) in MySQL

    CONSTRAINT taxdetails_pkey PRIMARY KEY ("AUTOID")
);

ALTER TABLE taxdetails OWNER TO firefly_app;
