-- Per-user printer assignment by role. Machine-local.
-- Note user_id is varchar(30) here but varchar(40) on pos_user_mode_prefs and
-- user_print_formats; mirrored as declared.

CREATE TABLE IF NOT EXISTS user_printers (
    "id"            integer      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id"       varchar(30)  NOT NULL,
    "printer_type"  varchar(6)   NOT NULL,
    "mode"          varchar(7)   NOT NULL DEFAULT 'network',
    "name"          varchar(255),
    "ip_address"    varchar(50),
    "port"          integer,
    "paper_width"   varchar(20)  DEFAULT '80mm',
    "type"          varchar(50)  DEFAULT 'EPSON',
    "character_set" varchar(50)  DEFAULT 'PC437_USA',
    "timeout_ms"    integer      DEFAULT 5000,
    "is_active"     smallint     DEFAULT 1,
    "PrinterId"     integer,
    "created_at"    timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
    "updated_at"    timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),

    CONSTRAINT user_printers_pkey PRIMARY KEY ("id"),
    CONSTRAINT uk_user_printer UNIQUE ("user_id", "printer_type"),
    CONSTRAINT chk_user_printers_printer_type CHECK ("printer_type" IN ('bill', 'parcel', 'kot', 'bar', 'pickup')),
    CONSTRAINT chk_user_printers_mode         CHECK ("mode" IN ('network', 'usb', 'pdf', 'kiosk'))
);

DROP TRIGGER IF EXISTS user_printers_set_updated_at ON user_printers;
CREATE TRIGGER user_printers_set_updated_at
    BEFORE UPDATE ON user_printers
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

ALTER TABLE user_printers OWNER TO firefly_app;
