-- Per-user override of the bill print engine. `kind` is a plain varchar(20) in
-- MySQL, not an enum, unlike the visually similar print_templates.kind.

CREATE TABLE IF NOT EXISTS user_print_formats (
    "id"          integer      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id"     varchar(40)  NOT NULL,
    "kind"        varchar(20)  NOT NULL DEFAULT 'bill',
    "engine"      varchar(8)   NOT NULL DEFAULT 'inherit',
    "template_id" integer,
    "is_active"   smallint     NOT NULL DEFAULT 1,
    "created_at"  timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),
    "updated_at"  timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),

    CONSTRAINT user_print_formats_pkey PRIMARY KEY ("id"),
    CONSTRAINT uk_upf_user_kind UNIQUE ("user_id", "kind"),
    CONSTRAINT chk_user_print_formats_engine CHECK ("engine" IN ('inherit', 'escpos', 'html', 'compiled'))
);

DROP TRIGGER IF EXISTS user_print_formats_set_updated_at ON user_print_formats;
CREATE TRIGGER user_print_formats_set_updated_at
    BEFORE UPDATE ON user_print_formats
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

ALTER TABLE user_print_formats OWNER TO firefly_app;
