-- POS operators.
--
-- "user" is a RESERVED WORD in PostgreSQL. Unquoted it resolves to the
-- CURRENT_USER function, so every reference -- DDL, queries, src/api/*.ts --
-- must write it as "user". This is the one table name in the schema that cannot
-- be spelled bare.
--
-- Password is stored in the clear, same caveat as ledger.mypassword.

CREATE TABLE IF NOT EXISTS "user" (
    "user_id"            integer     NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "UserId"             varchar(20) NOT NULL,
    "OrganizationCode"   varchar(4)  NOT NULL,
    "Name"               varchar(50) NOT NULL,
    "UserName"           varchar(50) NOT NULL,
    "Password"           varchar(500) NOT NULL,
    "Phone"              varchar(15) NOT NULL,
    "DefSOBillType"      varchar(20) NOT NULL,
    "DefSOCBillType"     varchar(20) NOT NULL,
    "DefSIBillType"      varchar(20) NOT NULL,
    "DefRVBillType"      varchar(20) NOT NULL,
    "DefPVBillType"      varchar(20) NOT NULL,
    "DefPOBillType"      varchar(20) NOT NULL,
    "DefSRBillType"      varchar(20) NOT NULL,
    "DefJVBillType"      varchar(20) NOT NULL,
    "SaleTaxIncDiscount" smallint    NOT NULL,
    "DefCashLedger"      varchar(20) NOT NULL,
    "IsAdmin"            smallint    NOT NULL,  -- tinyint(4) in MySQL, not tinyint(1)
    -- MySQL declares this "Routid", lowercase 'id'. Spelled "RoutId" here, per the
    -- README rule that the API payload's spelling wins: every PHP reference uses
    -- RoutId, both the writes in insert_user and the login read at
    -- firefly_api.php line 4614, which names it in the select list -- so MySQL
    -- already emits "RoutId" on the wire and only the DDL disagrees. Unquoted
    -- MySQL identifiers hide the difference; quoted PostgreSQL ones do not, and
    -- "Routid" here would make insert_user fail outright.
    "RoutId"             varchar(20) NOT NULL,
    "UseOnlyRoutLedgers" smallint    NOT NULL DEFAULT 0,
    "DefSaleRate"        varchar(20) NOT NULL,
    "DefWarehouseId"     varchar(20) NOT NULL,
    "DefCardBank"        varchar(20) NOT NULL,

    CONSTRAINT user_pkey PRIMARY KEY ("user_id")
);

ALTER TABLE "user" OWNER TO firefly_app;
