-- Which ledgers a user may not see. The largest table in the database (287 rows).
-- MySQL has a surrogate key but no uniqueness on (UserId, LedgerId); not adding
-- one, since duplicates are evidently tolerated today.

CREATE TABLE IF NOT EXISTS userledgerprivilege (
    "uspv_id"  integer     NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "UserId"   varchar(20) NOT NULL,
    "LedgerId" varchar(20) NOT NULL,
    "Block"    smallint    NOT NULL,

    CONSTRAINT userledgerprivilege_pkey PRIMARY KEY ("uspv_id")
);

ALTER TABLE userledgerprivilege OWNER TO firefly_app;
